exports.ERROR_CODE = {
  SOMETHING_WENT_WRONG: 101,
  DETAILS_NOT_FOUND: 102,
  TYPE_NOT_FOUND: 103,
  DETAIL_NOT_SAVED: 104,
  CAPTCHA_VERIFICATION_FAILED: 105,
  DETAIL_NOT_UPDATED: 106,
  DATA_NOT_FOUND: 107,
  IMAGE_NOT_DELETED: 108,
  PROVIDE_VALID_ID_FOR_AUTHORIZATION_IN_HEADER: 109,
};

exports.USER_ERROR_CODE = {
  USER_NOT_CREATED: 201,
};
