exports.ERROR_CODE = {
  SOMETHING_WENT_WRONG: 101,
  DETAILS_NOT_FOUND: 102,
  TYPE_NOT_FOUND: 103,
  DETAIL_NOT_SAVED: 104,
  CAPTCHA_VERIFICATION_FAILED: 105,
  DETAIL_NOT_UPDATED: 106,
  DATA_NOT_FOUND: 107,
  IMAGE_NOT_DELETED: 108,
  PROVIDE_VALID_ID_FOR_AUTHORIZATION_IN_HEADER: 109,
};

exports.USER_ERROR_CODE = {
  USER_NOT_CREATED: 201,
  EMAIL_ALREADY_TAKEN: 202,
  USERNAME_ALREADY_TAKEN: 203,
  USER_DETAILS_NOT_FOUND: 204,
  FAILED_TO_UPDATE_USER: 205,
  FAILED_TO_DELETE_USER: 206,
  FAILED_TO_RETRIVE_USERS: 207,
};

exports.CATEGORY_ERROR_CODE = {
  CATEGORY_NOT_CREATED: 301,
  CATEGORY_ALREADY_EXISTS: 302,
  CATEGORY_DETAILS_NOT_FOUND: 303,
  FAILED_TO_UPDATE_CATEGORY: 304,
  FAILED_TO_DELETE_CATEGORY: 305,
  FAILED_TO_RETRIEVE_CATEGORIES: 306,
};
