exports.USER_MESSAGE_CODE = {
  USER_CREATED_SUCCESSFULLY: 101,
  USER_DETAILS_RETRIVED_SUCCESSFULLY: 102,
  USER_DETAILS_UPDATED_SUCCESSFULLY: 103,
  USER_DELETED_SUCCESSFULLY: 104,
  USERS_RETRIVED_SUCCESSFULLY: 105,
};

exports.CATEGORY_MESSAGE_CODE = {
  CATEGORY_CREATED_SUCCESSFULLY: 201,
  CATEGORY_DETAILS_RETRIEVED_SUCCESSFULLY: 202,
  CATEGORY_UPDATED_SUCCESSFULLY: 203,
  CATEGORY_DELETED_SUCCESSFULLY: 204,
  CATEGORIES_RETRIEVED_SUCCESSFULLY: 205,
};